-- Seed des 21 jours de menus — idempotent via ON CONFLICT DO UPDATE
INSERT INTO meal_plans (jour, semaine, nom_jour, is_weekend, petit_dejeuner, collation_matin, dejeuner, collation_apres_midi, diner, astuce_umami)
VALUES
  (1, 1, 'Mise en orbite', false,
   '2 kiwis + 1 orange + poignée de noix',
   '1 pomme',
   'Salade de quinoa : quinoa, concombre, tomates cerise, avocat, jus de citron, huile d''olive, graines de sésame. Pincée de sel fumé.',
   '1 banane + 3 amandes',
   'Poêlée de courgettes, poireaux, champignons de Paris. Riz basmati. Une cuillère à café de tamari en fin de cuisson.',
   'Le tamari (sauce soja sans gluten) apporte un umami profond. Ajoutez-le hors du feu — jamais pendant la cuisson.'),

  (2, 1, 'Douceur verte', false,
   '1 mangue + 1 poire + noisettes concassées',
   '1 clémentine',
   'Velouté froid de concombre à l''avocat : mixer concombre, avocat, jus de citron, menthe. Graines de courge + pincée de levure maltée.',
   '1 poignée de raisins',
   'Purée de patate douce + chou-fleur rôti à l''ail et curcuma. Graines de tournesol. Filet d''huile de sésame grillé.',
   'La levure maltée (ou nutritionnelle) donne un goût fromagé/umami sans produits laitiers. À saupoudrer en finition.'),

  (3, 1, 'Feu doux', false,
   'Bol de fruits rouges (fraises, myrtilles) + 1 figue sèche + noix de pécan',
   '1 orange',
   'Salade tiède de lentilles corail + fenouil cru râpé + dés d''avocat + persil. Vinaigrette : huile d''olive, vinaigre de cidre, 1/2 c.c. de miso blanc délayé.',
   '1 kiwi',
   'Poireaux vapeur + purée de céleri-rave au lait de coco. Ciboulette et poudre de shiitake.',
   'Poudre de shiitake : umami intense sur purées. Le miso : ne jamais chauffer au-delà de 65°C pour préserver ses enzymes vivantes.'),

  (4, 1, 'Soleil d''Orient', false,
   '1/2 papaye + 1 orange + pistaches',
   '1 poire',
   'Bowl indien : riz thaï, pois chiches rôtis au curry, carottes râpées, coriandre fraîche, jus de citron vert. Sauce tahini-citron.',
   '1 pomme + 5 amandes',
   'Soupe de lentilles vertes aux tomates et épinards. Cumin, gingembre, ail. Filet de citron au moment du service.',
   'Le tahini dilué (eau + citron + ail) : sauce légère umami qui transforme n''importe quel bowl.'),

  (5, 1, 'Profondeur marine', false,
   '2 bananes + myrtilles + noix du Brésil',
   '1 clémentine',
   'Salade tiède de riz complet, algues wakamé réhydratées, concombre, graines de sésame, gingembre frais râpé. Sauce : tamari + vinaigre de riz + huile de sésame.',
   '1 poire',
   'Potimarron rôti à l''huile de coco + quinoa aux herbes (persil, ciboulette, menthe). Graines de courge torréfiées.',
   'Algues wakamé (réhydratées 5 min eau froide) : umami naturel de la mer, riches en minéraux et iode.'),

  (6, 1, 'Week-end libre', true,
   'Fruits de saison au choix + oléagineux (amandes, noix, noisettes)',
   '1 fruit au choix',
   'Repas libre Verissimo : légumes + légumineuses ou céréale sans gluten. Pas de produit animal ni laitier.',
   'Fruits + poignée de noix ou noisettes',
   'Repas libre Verissimo : légumes cuisinés selon vos envies du moment.',
   'Profitez du week-end pour explorer de nouvelles épices et aromates dans votre cuisine.'),

  (7, 1, 'Week-end libre', true,
   'Fruits de saison au choix + oléagineux (amandes, noix, noisettes)',
   '1 fruit au choix',
   'Repas libre Verissimo : légumes + légumineuses ou céréale sans gluten. Pas de produit animal ni laitier.',
   'Fruits + poignée de noix ou noisettes',
   'Repas libre Verissimo : légumes cuisinés selon vos envies du moment.',
   'Profitez du week-end pour explorer de nouvelles épices et aromates dans votre cuisine.'),

  (8, 2, 'Explosion verte', false,
   '1 avocat en tranches + 1/2 pamplemousse + graines de courge',
   '1 pomme verte',
   'Green bowl : quinoa, épinards frais, concombre, avocat, edamame, graines de tournesol. Sauce : tahini + citron vert + gingembre + eau.',
   '1 kiwi + 3 noix',
   'Poêlée de champignons shiitake et champignons de Paris + riz basmati. Tamari, ail, échalote. Persil frais en finition.',
   'Shiitake poêlé à feu très vif : source naturelle de glutamate (umami pur). Ne pas surcharger la poêle — ils doivent dorer, pas bouillir.'),

  (9, 2, 'Crémeux du soleil', false,
   '1 mangue + 1 orange + noisettes',
   '1 abricot ou 1 figue selon saison',
   'Soupe crémeuse de courge butternut + lait de coco + gingembre + curcuma. Graines de courge torréfiées + levure maltée.',
   '1 poire',
   'Salade tiède de pois chiches + tomates cerise + olives noires + roquette + herbes. Vinaigrette : vinaigre balsamique + huile d''olive + moutarde.',
   'Olives noires à l''huile : umami naturel + acides gras bénéfiques. Éviter les olives en saumure industrielle.'),

  (10, 2, 'Temple thaï', false,
   'Bol de litchis + framboises + pistaches',
   '1 banane',
   'Bowl thaï : riz jasmin, carottes spiralisées, chou rouge émincé, menthe, coriandre, noix de cajou. Sauce : tamari + citron vert + gingembre + piment doux.',
   '1 poire + amandes',
   'Curry doux de légumes (poivron, courgette, épinards, tomates) au lait de coco + riz thaï. Coriandre fraîche.',
   'Lait de coco entier ajouté en fin de cuisson : onctuosité + rondeur qui équilibre les épices.'),

  (11, 2, 'Profondeur terrienne', false,
   '2 prunes + 1 poire + noix de cajou',
   '1 orange',
   'Salade de riz complet + légumes rôtis (poivrons, aubergine, oignons) + pesto vert (basilic, pignons, huile d''olive, levure maltée, citron).',
   '1 pomme',
   'Velouté de brocolis et petits pois. Graines de sésame. Quelques gouttes d''huile de sésame grillé en finition.',
   'Pesto végétalien avec levure maltée : 2 c.s. remplacent le parmesan. Umami + protéines + vitamines B. Ne pas chauffer.'),

  (12, 2, 'Lumière méditerranéenne', false,
   '1 grappe de raisin + 1 kiwi + amandes effilées',
   '1 figue fraîche',
   'Salade grecque revisitée : tomates, concombre, olives noires, oignon rouge, câpres, origan, quinoa. Huile d''olive généreuse + citron.',
   '1 banane',
   'Courgettes farcies aux lentilles vertes, tomates et herbes fraîches. Cuire au four 20 min. Filet de tahini en finition.',
   'Câpres : umami intense + acidité naturelle. Toujours ajouter crus en finition pour préserver leur puissance.'),

  (13, 2, 'Week-end libre', true,
   'Fruits de saison au choix + oléagineux (amandes, noix, noisettes)',
   '1 fruit au choix',
   'Repas libre Verissimo : légumes + légumineuses ou céréale sans gluten. Pas de produit animal ni laitier.',
   'Fruits + poignée de noix ou noisettes',
   'Repas libre Verissimo : légumes cuisinés selon vos envies du moment.',
   'Profitez du week-end pour explorer de nouvelles épices et aromates dans votre cuisine.'),

  (14, 2, 'Week-end libre', true,
   'Fruits de saison au choix + oléagineux (amandes, noix, noisettes)',
   '1 fruit au choix',
   'Repas libre Verissimo : légumes + légumineuses ou céréale sans gluten. Pas de produit animal ni laitier.',
   'Fruits + poignée de noix ou noisettes',
   'Repas libre Verissimo : légumes cuisinés selon vos envies du moment.',
   'Profitez du week-end pour explorer de nouvelles épices et aromates dans votre cuisine.'),

  (15, 3, 'Fondations', false,
   '2 kiwis + 1 poire + 1 figue sèche + amandes',
   '1 pomme',
   'Buddha bowl : riz complet, lentilles beluga (noires), carottes rôties, épinards frais, graines de courge, avocat. Sauce tahini-citron-ail.',
   '1 banane + pistaches',
   'Soupe de panais et carottes au gingembre et lait de coco. Poudre de shiitake. Coriandre fraîche.',
   'Le panais apporte une douceur terreuse remarquable en soupe. Associez-le toujours au gingembre pour l''équilibre.'),

  (16, 3, 'Lumière du Nord', false,
   'Graines de grenade + 1 orange + noix du Brésil',
   '1 poire',
   'Salade nordique : quinoa, betteraves cuites en cubes, aneth frais, câpres, oignon rouge, graines de courge. Vinaigrette : huile d''olive + vinaigre de cidre + moutarde à l''ancienne.',
   '1 kiwi + 3 amandes',
   'Lasagnes végétales : lamelles de courgettes (remplacent les pâtes) + sauce tomate maison aux herbes + pois chiches écrasés + levure maltée + basilic. Enfourner 25 min.',
   'Moutarde à l''ancienne (en grains) : umami léger + acidité + texture croquante. Idéale pour émulsionner les vinaigrettes.'),

  (17, 3, 'Énergie dorée', false,
   '1 papaye + 1 mangue + noix de cajou',
   '1 orange',
   'Golden bowl : riz jasmin, lentilles corail, carottes, oignons caramélisés 30 min au curcuma. Coriandre fraîche + citron.',
   '1 poire',
   'Fenouil braisé au four + tomates fraîches + olives noires + thym. Polenta crémeuse au bouillon de légumes.',
   'Oignon caramélisé 30 min à feu très doux : sucres naturels libérés = umami sucré-salé incomparable.'),

  (18, 3, 'Racines profondes', false,
   'Compotée de pommes tiède + noisettes + 1 c.c. cannelle',
   '1 kiwi',
   'Maki bowl : riz à sushi (vinaigre de riz), feuilles de nori en lanières, concombre, avocat, carottes, graines de sésame. Sauce : tamari + gingembre + huile de sésame.',
   '1 poire + amandes',
   'Légumes racines rôtis au four (panais, betterave, carottes, céleri-rave) + pois chiches croustillants au four (cumin + piment). Herbes fraîches.',
   'Nori en lanières sur le riz : umami marin + minéraux + iode instantanés.'),

  (19, 3, 'Arc-en-ciel', false,
   '1 banane + framboises + myrtilles + graines de lin moulues',
   '1 pomme',
   'Bowl arc-en-ciel : millet, carottes râpées crues, chou rouge émincé, betterave crue râpée, avocat, graines de tournesol. Sauce tahini-citron-ail.',
   '1 orange + pistaches',
   'Soupe de haricots blancs au romarin + tomates séchées à l''huile. Légumes verts vapeur. Huile d''olive première pression.',
   'Tomates séchées à l''huile : concentration maximale de glutamate naturel. Quelques morceaux transforment une soupe simple en plat d''une profondeur étonnante.'),

  (20, 3, 'Week-end libre', true,
   'Fruits de saison au choix + oléagineux (amandes, noix, noisettes)',
   '1 fruit au choix',
   'Repas libre Verissimo : légumes + légumineuses ou céréale sans gluten. Pas de produit animal ni laitier.',
   'Fruits + poignée de noix ou noisettes',
   'Repas libre Verissimo : légumes cuisinés selon vos envies du moment.',
   'Profitez du week-end pour explorer de nouvelles épices et aromates dans votre cuisine.'),

  (21, 3, 'Célébration', true,
   'Grande assiette de fruits de saison au choix + mélange de noix + graines',
   '1 fruit au choix',
   'Risotto de millet aux champignons shiitake + huile de truffe bio (quelques gouttes) + levure maltée + persil. Bouillon de légumes maison riche.',
   'Smoothie : banane + myrtilles + eau de coco',
   'Légumes de fête rôtis au four (patate douce, carottes multicolores, betteraves, poivrons, oignons). Sauce tahini-citron-herbes. Purée de châtaignes.',
   'Quelques gouttes d''huile de truffe sur le risotto fini : umami de luxe. Une seule utilisation suffit pour transformer un plat simple en moment d''exception — c''est votre jour 21, célébrez-le.')

ON CONFLICT (jour) DO UPDATE SET
  semaine             = EXCLUDED.semaine,
  nom_jour            = EXCLUDED.nom_jour,
  is_weekend          = EXCLUDED.is_weekend,
  petit_dejeuner      = EXCLUDED.petit_dejeuner,
  collation_matin     = EXCLUDED.collation_matin,
  dejeuner            = EXCLUDED.dejeuner,
  collation_apres_midi = EXCLUDED.collation_apres_midi,
  diner               = EXCLUDED.diner,
  astuce_umami        = EXCLUDED.astuce_umami,
  updated_at          = now();
