export const verissimoPrinciples = [
  {
    id: 1,
    title: "La mastication",
    icon: "🦷",
    shortDesc: "La digestion commence dans ta bouche, pas dans ton estomac.",
    fullDesc:
      "Tu disposes de 6 glandes salivaires qui produisent jusqu'à 1 litre de salive par jour. Si tu ne mastiques pas, tu n'en produis que 200 à 300 ml — insuffisant pour digérer correctement. Résultat : ballonnements, fatigue, flatulences. Bien mastiquer divise le temps de digestion par 2 et libère une énergie considérable.",
    rule: "Mâche chaque bouchée 20 à 30 fois minimum. Pose ta fourchette entre chaque bouchée.",
    impact: "Anti-ballonnements, meilleure assimilation des nutriments, flatulences supprimées",
  },
  {
    id: 2,
    title: "Dissocier les aliments",
    icon: "⚗️",
    shortDesc: "Certains aliments s'associent, d'autres se sabotent mutuellement.",
    fullDesc:
      "Protéines animales et céréales dans le même repas créent une incompatibilité : la digestion passe de 2-3h à 6-8h. L'estomac fermente au lieu de digérer, générant acide, ballonnements et vieillissement cellulaire accéléré.",
    rules: [
      "Œufs, poisson, viande → avec légumes et salade UNIQUEMENT",
      "Céréales (riz, quinoa...) → avec légumes, jamais avec protéines animales",
      "Légumineuses → associer à une céréale (riz + lentilles = protéines complètes)",
      "Fruits → seuls, à distance des repas (sauf petit-déjeuner avec oléagineux)",
      "Melon et pastèque → toujours seuls, jamais mélangés",
      "Oléagineux (amandes, noix...) → avec légumes et crudités",
    ],
    impact: "Digestion réduite à 90 min, énergie libérée, ventre plat, perte de poids naturelle",
  },
  {
    id: 3,
    title: "Respecter les temps de digestion",
    icon: "⏱️",
    shortDesc: "Ne remange pas tant que ton estomac n'a pas fini.",
    fullDesc:
      "Chaque famille d'aliments a son temps de transit stomacal. Manger avant la fin de la digestion précédente, c'est enchaîner deux jours de travail sans pause. Le système digestif s'épuise, le pH dérègle, l'inflammation s'installe.",
    digestionTimes: [
      { food: "Eau & jus", time: "10-15 min" },
      { food: "Fruits frais", time: "30-60 min" },
      { food: "Légumes feuilles", time: "40 min" },
      { food: "Légumes racines", time: "50 min" },
      { food: "Céréales", time: "90 min" },
      { food: "Légumineuses", time: "90 min" },
      { food: "Oléagineux", time: "2h30-3h" },
      { food: "Poisson blanc", time: "30 min" },
      { food: "Poisson gras", time: "45-60 min" },
      { food: "Volaille", time: "2h" },
      { food: "Bœuf / agneau", time: "3-4h" },
      { food: "Fruits de mer", time: "8h" },
    ],
    rule: "Ne grignote pas. Entre les repas, bois de l'eau. Rien d'autre.",
    impact: "Système nerveux au repos, organes qui se régénèrent, énergie entre les repas",
  },
  {
    id: 4,
    title: "L'équilibre acido-basique",
    icon: "⚖️",
    shortDesc: "Un corps trop acide est un corps qui s'abîme.",
    fullDesc:
      "Chaque organe fonctionne à un pH précis. Les incompatibilités alimentaires, le stress, le sucre et les protéines animales en excès génèrent une hyperacidité chronique qui dérègle les enzymes, accélère le vieillissement cellulaire et crée de l'inflammation. Le programme Verissimo est conçu pour rééquilibrer le pH progressivement.",
    acidicFoods: [
      "Viande rouge",
      "Charcuterie",
      "Fromage",
      "Sucre raffiné",
      "Café",
      "Alcool",
      "Produits industriels",
    ],
    alkalineFoods: [
      "Légumes verts",
      "Fruits frais",
      "Herbes aromatiques",
      "Jus de légumes",
      "Amandes",
      "Graines germées",
    ],
    rule: "Le repas du soir est toujours 100 % végétalien et alcalin. Pas de protéines animales après 18h.",
    impact: "Réduction des inflammations, douleurs articulaires diminuées, teint lumineux, sommeil amélioré",
  },
  {
    id: 5,
    title: "Manger vivant",
    icon: "🌱",
    shortDesc: "Les aliments crus concentrent l'énergie vitale que ton corps assimile directement.",
    fullDesc:
      "La chaleur au-delà de 42°C détruit les enzymes, les vitamines thermosensibles et réduit la densité nutritionnelle. Une alimentation vivante — crudités, jus frais, fruits, graines germées — transmet directement son énergie à tes cellules sans surcharger les organes digestifs. La cure Verissimo intègre du cru à chaque repas.",
    rule: "Commence chaque repas par une crudité ou un jus. Ne chauffe jamais l'huile d'olive — verse-la à froid après cuisson.",
    impact: "Vitamines et enzymes préservées, énergie cellulaire maximisée, immunité renforcée",
  },
  {
    id: 6,
    title: "L'hydratation",
    icon: "💧",
    shortDesc: "L'eau est le premier aliment détox. Elle transporte, filtre, élimine.",
    fullDesc:
      "Le corps est constitué à 70 % d'eau. Une légère déshydratation (1 à 2 %) suffit à ralentir le métabolisme, épaissir le sang et fatiguer les reins. Boire en dehors des repas (et non pendant) préserve les sucs digestifs et accélère l'élimination des toxines.",
    rules: [
      "1,5 à 2 litres d'eau pure par jour minimum",
      "Boire au réveil : 1 verre d'eau tiède avec jus de citron frais",
      "Ne pas boire pendant le repas (dilue les sucs digestifs)",
      "Attendre 30 min après le repas avant de boire",
      "Jus de légumes frais centrifugés : comptent dans l'hydratation",
    ],
    impact: "Élimination accélérée, peau hydratée, énergie stable, transit régulé",
  },
  {
    id: 7,
    title: "Le repos digestif",
    icon: "🌙",
    shortDesc: "Ce n'est pas en mangeant plus que tu te régénères — c'est en digérant moins.",
    fullDesc:
      "40 % de l'énergie globale de l'organisme est consacrée à la digestion. En réduisant la fréquence des repas et en respectant les intervalles, tu libères cette énergie pour la régénération cellulaire, la réparation des tissus et l'élimination des toxines stockées. Le corps se guérit lui-même quand on lui en laisse l'opportunité.",
    rules: [
      "3 repas par jour maximum — pas de grignotage",
      "Minimum 4h entre chaque repas",
      "Dîner avant 20h idéalement",
      "12h de repos digestif nocturne minimum (ex : dîner 19h → petit-déj 7h)",
      "En cas de faim entre les repas : eau ou tisane, jamais solide",
    ],
    impact: "Perte de poids naturelle, énergie retrouvée, sommeil réparateur, clarté mentale",
  },
]
