// jour-data.jsx — backtoenergy · les 21 jours de menus (méthode Verissimo)
// Conforme aux règles : pas de protéine animale + féculent, pas de double protéine animale,
// pas de laitage de vache, pas de blé/gluten ni sucre raffiné, fruits toujours seuls (matin/encas).
// Source statique consommée par jour-screen.jsx via window.BTE_DAYS.

const DAYS = [
// ============================ SEMAINE 1 · Détox & Purification ============================
// J1 — démarrage tout en douceur (trio de référence, photos réelles)
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Fruits & oléagineux, miel-citron",
    sensation: "Du sucré qui vient du fruit, le croquant des oléagineux, une pointe de miel et de citron qui réveille. Léger mais rassasiant — l'énergie monte tout doucement.",
    ingredients: [["Fruits de saison", "1 bol"], ["Amandes & noix", "1 poignée"], ["Graines de courge", "1 c. à s."], ["Miel", "1 c. à c."], ["Citron", "quelques gouttes"]],
    swaps: ["Pas d'amandes ? → noisettes ou noix de cajou", "Sans miel ? → quelques raisins secs pour le sucré"],
    why: "Le matin, le corps aime la légèreté : des fruits pour l'énergie qui vient vite, des oléagineux pour tenir jusqu'au déjeuner. Rien de lourd à digérer pour bien démarrer.",
    steps: ["Lave et coupe les fruits de saison en morceaux dans un bol.", "Concasse grossièrement les amandes et les noix, parsème-les dessus avec les graines.", "Arrose d'un filet de miel et de quelques gouttes de citron. Mélange délicatement, et déguste."] },
  { key: "dej", slot: "Déjeuner", title: "Buddha bowl de printemps",
    sensation: "Du croquant, du fondant, des couleurs : ça nourrit pour de vrai. Tu sors de table calé mais léger, sans le coup de barre de 14 h.",
    ingredients: [["Quinoa cuit", "80 g"], ["Avocat", "½"], ["Radis", "4"], ["Jeunes pousses", "1 poignée"], ["Graines de courge", "1 c. à s."], ["Huile d'olive + citron", "filet"]],
    swaps: ["Pas de quinoa ? → sarrasin, même moelleux", "Sans avocat ? → une poignée de pois chiches rôtis"],
    why: "Que du végétal ici : une céréale, des légumes, de bonnes graisses. Pas de protéine animale avec le féculent — la digestion reste tranquille et l'énergie tient tout l'après-midi.",
    steps: ["Dépose le quinoa cuit, tiède ou froid, au fond du bol.", "Ajoute l'avocat en lamelles, les radis émincés et les jeunes pousses.", "Parsème de graines de courge, arrose d'huile d'olive et de citron. Mélange juste avant de manger."] },
  { key: "din", slot: "Dîner", title: "Dal de lentilles corail au lait de coco",
    sensation: "Chaud, doré, parfumé : les épices réchauffent sans peser. Une assiette douce, parfaite pour finir la journée et préparer une nuit tranquille.",
    ingredients: [["Lentilles corail", "80 g"], ["Lait de coco", "15 cl"], ["Tomate", "1"], ["Oignon", "½"], ["Ail", "1 gousse"], ["Gingembre frais", "1 cm"], ["Curcuma, cumin, coriandre", "1 c. à c."]],
    swaps: ["Pas de lentilles corail ? → lentilles vertes, un peu plus de mâche", "Sans lait de coco ? → crème de cajou, même douceur"],
    why: "Les lentilles, c'est une protéine 100 % végétale : rien qui alourdit la digestion du soir. Le lait de coco remplace la crème — zéro laitage de vache — et le tout est naturellement sans gluten.",
    steps: ["Fais revenir l'oignon, l'ail et le gingembre dans un filet d'huile avec les épices, jusqu'à ce que ça embaume.", "Ajoute la tomate en dés et les lentilles corail rincées, puis couvre d'eau et de lait de coco.", "Laisse mijoter 15 à 20 min jusqu'à ce que les lentilles fondent. Parsème de coriandre fraîche."] }
] },
// J2
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Smoothie vert pomme-épinard-gingembre",
    photo: "images/pdj-smoothie-vert.jpg",
    sensation: "Frais, vif, légèrement piquant grâce au gingembre. Ça réveille en douceur et hydrate dès le matin.",
    ingredients: [["Pomme verte", "1"], ["Épinards frais", "1 poignée"], ["Concombre", "¼"], ["Gingembre frais", "1 cm"], ["Citron", "½"], ["Eau de source", "20 cl"]],
    swaps: ["Pas d'épinards ? → mâche ou jeunes pousses", "Trop piquant ? → enlève le gingembre, ajoute de la menthe"],
    why: "Un jus vert au réveil, c'est la signature détox : beaucoup d'eau, des végétaux qui drainent, et juste assez de fruit pour le goût. Léger, le corps n'a presque rien à digérer.",
    steps: ["Lave tous les ingrédients et coupe la pomme et le concombre en morceaux.", "Mixe le tout avec l'eau jusqu'à obtenir une texture lisse.", "Ajoute un trait de citron et bois aussitôt, bien frais."] },
  { key: "dej", slot: "Déjeuner", title: "Salade de quinoa, concombre & pois chiches",
    photo: "images/dej-quinoa-concombre.jpg",
    sensation: "Frais et croquant, parfumé à la menthe. Une assiette qui désaltère autant qu'elle nourrit.",
    ingredients: [["Quinoa cuit", "80 g"], ["Pois chiches cuits", "3 c. à s."], ["Concombre", "½"], ["Menthe fraîche", "quelques feuilles"], ["Citron", "½"], ["Huile d'olive", "filet"]],
    swaps: ["Pas de quinoa ? → millet ou sarrasin", "Pas de menthe ? → persil ou coriandre"],
    why: "Céréale et légumineuse ensemble, sans aucune protéine animale : un duo végétal complet qui digère sans fermenter, et qui tient tout l'après-midi.",
    steps: ["Mélange le quinoa refroidi avec les pois chiches égouttés.", "Ajoute le concombre en petits dés et la menthe ciselée.", "Assaisonne d'huile d'olive et de citron, sale légèrement et mélange."] },
  { key: "din", slot: "Dîner", title: "Velouté de courgette au basilic",
    photo: "images/din-veloute-courgette.jpg",
    sensation: "Onctueux, vert tendre, réconfortant sans être lourd. Idéal pour une soirée légère.",
    ingredients: [["Courgettes", "2"], ["Oignon", "½"], ["Bouillon de légumes", "40 cl"], ["Basilic frais", "quelques feuilles"], ["Huile d'olive", "filet"], ["Graines de courge", "1 c. à s."]],
    swaps: ["Pas de courgette ? → brocoli, même douceur", "Plus crémeux ? → 1 c. à s. de purée de cajou"],
    why: "Un dîner tout en légumes et en eau : facile à digérer le soir, sans féculent ni protéine animale pour ne pas charger la nuit. Le basilic apporte le parfum.",
    steps: ["Fais suer l'oignon dans l'huile, ajoute les courgettes en rondelles.", "Couvre de bouillon et laisse cuire 15 min, puis mixe.", "Ajoute le basilic, mixe encore et parsème de graines de courge au moment de servir."] }
] },
// J3
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Bol de fruits rouges & graines de chia",
    sensation: "Acidulé, frais, avec la petite mâche des graines qui ont gonflé. Doux et rassasiant à la fois.",
    ingredients: [["Fruits rouges", "1 bol"], ["Graines de chia", "1 c. à s."], ["Lait de coco", "10 cl"], ["Citron", "quelques gouttes"]],
    swaps: ["Hors saison ? → fruits rouges surgelés, décongelés", "Pas de chia ? → graines de lin moulues"],
    why: "Les fruits rouges sont parmi les plus riches en antioxydants et pauvres en sucre. Servis seuls le matin, avec le chia qui cale, ils respectent la règle « fruits toujours seuls ».",
    steps: ["La veille, mélange le chia avec le lait de coco et laisse gonfler au frais.", "Le matin, dépose les fruits rouges par-dessus.", "Ajoute quelques gouttes de citron et déguste frais."] },
  { key: "dej", slot: "Déjeuner", title: "Assiette d'avocat, roquette & graines de tournesol",
    sensation: "Crémeux et poivré, vivifiant. Du cru qui croque, des bonnes graisses qui rassasient.",
    ingredients: [["Avocat", "1"], ["Roquette", "2 poignées"], ["Graines de tournesol", "1 c. à s."], ["Citron", "½"], ["Huile d'olive", "filet"], ["Graines germées", "1 poignée"]],
    swaps: ["Pas de roquette ? → mâche ou épinards crus", "Plus consistant ? → ajoute du concombre et des radis"],
    why: "Un déjeuner cru et léger en pleine semaine détox : que des végétaux et de bonnes graisses, aucune cuisson, le système digestif se repose.",
    steps: ["Dispose la roquette dans une assiette, ajoute l'avocat en lamelles.", "Parsème de graines de tournesol et de graines germées.", "Arrose d'huile d'olive et de citron, donne un tour de moulin à poivre."] },
  { key: "din", slot: "Dîner", title: "Soupe miso-légumes & tofu",
    sensation: "Salin, réconfortant, plein d'umami. Un bol chaud qui apaise et prépare au sommeil.",
    ingredients: [["Miso de riz", "1 c. à s."], ["Tofu ferme", "100 g"], ["Carotte", "1"], ["Champignons", "4"], ["Algues wakamé", "1 pincée"], ["Oignon nouveau", "1"]],
    swaps: ["Pas de tofu ? → un peu plus d'algues et de champignons", "Pas de wakamé ? → quelques épinards"],
    why: "Le miso de riz est sans gluten et le tofu apporte une protéine végétale douce. Pas de laitage, pas de féculent lourd : un dîner tout léger et chaleureux.",
    steps: ["Chauffe de l'eau avec les carottes et les champignons émincés, sans bouillir trop fort.", "Hors du feu, délaye le miso dans un peu d'eau chaude puis reverse dans la casserole.", "Ajoute le tofu en dés, le wakamé et l'oignon nouveau ciselé. Sers aussitôt."] }
] },
// J4 — pic de détox, très léger
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Jus vert détox céleri-pomme-citron",
    sensation: "Net, presque tonique, une fraîcheur qui claque. Tu te sens rincé de l'intérieur.",
    ingredients: [["Céleri branche", "2 branches"], ["Pomme verte", "1"], ["Concombre", "½"], ["Citron", "1"], ["Persil", "quelques brins"]],
    swaps: ["Pas d'extracteur ? → mixe puis filtre au tamis", "Trop amer ? → un peu plus de pomme"],
    why: "En plein cœur de la phase de nettoyage, un jus vert très peu sucré laisse le système digestif quasiment au repos tout en hydratant et reminéralisant.",
    steps: ["Passe le céleri, le concombre et la pomme à l'extracteur.", "Ajoute le jus de citron et le persil mixé.", "Bois lentement, à jeun de préférence."] },
  { key: "dej", slot: "Déjeuner", title: "Soupe crue courgette-avocat & graines",
    sensation: "Vert, velouté, frais et nourrissant sans aucune cuisson. Doux pour le ventre.",
    ingredients: [["Courgette crue", "1"], ["Avocat", "½"], ["Citron", "½"], ["Basilic", "quelques feuilles"], ["Graines de courge", "1 c. à s."], ["Eau", "10 cl"]],
    swaps: ["Plus relevé ? → une pointe d'ail", "Sans avocat ? → 1 c. à s. de purée d'amande"],
    why: "Une soupe crue garde toutes les enzymes des végétaux : parfait pour une journée détox, sans féculent ni protéine animale, juste du frais qui hydrate.",
    steps: ["Mixe la courgette crue avec l'avocat, le citron, le basilic et l'eau.", "Rectifie l'assaisonnement avec une pincée de sel.", "Verse dans un bol et parsème de graines de courge."] },
  { key: "din", slot: "Dîner", title: "Bouillon de légumes & riz complet au gingembre",
    sensation: "Chaud, parfumé, un peu de tenue grâce au riz. Réconfortant après une journée légère.",
    ingredients: [["Riz complet cuit", "60 g"], ["Bouillon de légumes", "40 cl"], ["Carotte", "1"], ["Poireau", "½"], ["Gingembre frais", "1 cm"], ["Coriandre", "quelques brins"]],
    swaps: ["Pas de riz complet ? → riz semi-complet ou quinoa", "Plus de peps ? → un trait de citron vert"],
    why: "Après une journée très légère, un peu de riz complet réconforte sans lourdeur. Aucune protéine animale ici : la céréale et les légumes font tout le travail, en douceur.",
    steps: ["Fais chauffer le bouillon avec la carotte et le poireau émincés et le gingembre.", "Laisse cuire 12 min, puis ajoute le riz complet déjà cuit pour le réchauffer.", "Parsème de coriandre et sers bien chaud."] }
] },
// J5
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Compote pomme-poire à la cannelle & amandes",
    sensation: "Doux, fondant, parfumé à la cannelle. Une douceur tiède réconfortante au réveil.",
    ingredients: [["Pomme", "1"], ["Poire", "1"], ["Cannelle", "1 pincée"], ["Amandes", "1 poignée"], ["Citron", "quelques gouttes"]],
    swaps: ["Pas de poire ? → deux pommes", "Sans amandes ? → noisettes concassées"],
    why: "Une compote maison sans sucre ajouté : tout le sucré vient du fruit. Servie seule avec quelques amandes, elle reste dans la règle « fruits le matin, jamais en dessert ».",
    steps: ["Coupe les fruits en morceaux et fais-les compoter 10 min à couvert avec un fond d'eau.", "Écrase à la fourchette, ajoute la cannelle et un trait de citron.", "Parsème d'amandes concassées et déguste tiède."] },
  { key: "dej", slot: "Déjeuner", title: "Bowl de sarrasin, betterave & roquette",
    sensation: "Terreux et frais à la fois, la betterave sucrée, les noix qui croquent. Coloré et rassasiant.",
    ingredients: [["Sarrasin cuit", "80 g"], ["Betterave cuite", "1"], ["Roquette", "1 poignée"], ["Noix", "1 poignée"], ["Huile de noix", "filet"], ["Citron", "½"]],
    swaps: ["Pas de sarrasin ? → quinoa ou millet", "Pas de noix ? → graines de courge"],
    why: "Sarrasin (une « fausse céréale » sans gluten) et légumes, sans protéine animale : un déjeuner végétal complet, riche en fibres, qui ne fermente pas.",
    steps: ["Dépose le sarrasin tiède au fond du bol.", "Ajoute la betterave en dés et la roquette.", "Parsème de noix, arrose d'huile de noix et de citron."] },
  { key: "din", slot: "Dîner", title: "Curry de chou-fleur au lait de coco",
    sensation: "Crémeux, doré, doucement épicé. Un plat enveloppant qui réchauffe sans alourdir.",
    ingredients: [["Chou-fleur", "½"], ["Lait de coco", "15 cl"], ["Oignon", "½"], ["Curcuma & curry doux", "1 c. à c."], ["Gingembre", "1 cm"], ["Coriandre", "quelques brins"]],
    swaps: ["Pas de chou-fleur ? → brocoli ou courge", "Plus doux ? → moins de curry, plus de coco"],
    why: "Des légumes mijotés dans le lait de coco : pas de laitage de vache, pas de protéine animale le soir. Les épices réchauffent et facilitent la digestion.",
    steps: ["Fais revenir l'oignon et les épices, ajoute le chou-fleur en bouquets.", "Verse le lait de coco, couvre et laisse mijoter 15 min.", "Parsème de coriandre fraîche avant de servir."] }
] },
// J6
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Salade de fruits frais de saison",
    sensation: "Juteux, coloré, gorgé de fraîcheur. Le réveil le plus simple et le plus vif qui soit.",
    ingredients: [["Fruits de saison variés", "1 bol"], ["Menthe fraîche", "quelques feuilles"], ["Citron vert", "½"]],
    swaps: ["Envie de croquant ? → quelques graines de courge", "Plus parfumé ? → un peu de basilic"],
    why: "Des fruits seuls, crus et variés : la règle d'or du matin. Aucun mélange avec autre chose qui ralentirait la digestion — juste de l'énergie qui vient vite.",
    steps: ["Lave et coupe les fruits en morceaux réguliers.", "Ajoute la menthe ciselée et un trait de citron vert.", "Mélange délicatement et déguste aussitôt."] },
  { key: "dej", slot: "Déjeuner", title: "Œufs brouillés aux herbes & poêlée d'épinards",
    sensation: "Moelleux, fondant, parfumé aux herbes fraîches. Réconfortant et plein de protéines.",
    ingredients: [["Œufs", "2"], ["Épinards frais", "2 poignées"], ["Ciboulette & persil", "quelques brins"], ["Huile d'olive", "filet"], ["Ail", "1 gousse"]],
    swaps: ["Sans œufs ? → tofu brouillé au curcuma", "Pas d'épinards ? → blettes émincées"],
    why: "Une protéine animale (l'œuf) servie avec des légumes verts, sans aucun féculent : on respecte la règle « jamais protéine animale + féculent ». Léger et digeste.",
    steps: ["Fais tomber les épinards à la poêle avec l'ail et un filet d'huile.", "Bats les œufs, verse-les sur feu doux et remue jusqu'à texture crémeuse.", "Ajoute les herbes ciselées et sers avec les épinards."] },
  { key: "din", slot: "Dîner", title: "Velouté de petits pois à la menthe",
    sensation: "Vert vif, doux et sucré naturellement, une fraîcheur mentholée. Léger comme une caresse.",
    ingredients: [["Petits pois", "200 g"], ["Oignon nouveau", "1"], ["Bouillon de légumes", "35 cl"], ["Menthe fraîche", "quelques feuilles"], ["Huile d'olive", "filet"]],
    swaps: ["Pois surgelés ? → parfaits, plus rapides", "Plus onctueux ? → 1 c. à s. de purée de cajou"],
    why: "Un velouté tout végétal, sans féculent ni laitage : parfait le soir, il rassasie en douceur sans charger la digestion de la nuit.",
    steps: ["Fais suer l'oignon, ajoute les petits pois et le bouillon.", "Laisse cuire 8 min puis mixe avec la menthe.", "Rectifie l'assaisonnement, ajoute un filet d'huile d'olive et sers chaud."] }
] },
// J7 — fin de semaine 1
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Smoothie banane-myrtille-amande",
    sensation: "Velouté, sucré naturellement, gourmand. Un câlin du matin sans rien de lourd.",
    ingredients: [["Banane", "1"], ["Myrtilles", "1 poignée"], ["Lait d'amande", "20 cl"], ["Purée d'amande", "1 c. à c."], ["Cannelle", "1 pincée"]],
    swaps: ["Pas de myrtilles ? → fruits rouges mélangés", "Sans lait d'amande ? → lait de coco léger"],
    why: "Un smoothie de fruits avec du lait végétal : zéro laitage de vache. Servi le matin, le fruit est « seul » dans le repas, comme le veut la méthode.",
    steps: ["Mets la banane, les myrtilles et la purée d'amande dans le blender.", "Verse le lait d'amande et mixe jusqu'à onctuosité.", "Saupoudre de cannelle et bois frais."] },
  { key: "dej", slot: "Déjeuner", title: "Buddha bowl carottes rôties, quinoa & tahini",
    sensation: "Doré, fondant, la sauce tahini qui lie tout. Réconfortant et coloré.",
    ingredients: [["Quinoa cuit", "80 g"], ["Carottes", "2"], ["Pois chiches cuits", "3 c. à s."], ["Tahini", "1 c. à s."], ["Citron", "½"], ["Cumin", "1 pincée"]],
    swaps: ["Pas de tahini ? → purée d'amande détendue à l'eau", "Pas de quinoa ? → millet"],
    why: "Céréale, légumineuse et légumes, liés par une sauce au sésame : un bowl 100 % végétal, sans protéine animale ni laitage. La digestion reste sereine.",
    steps: ["Rôtis les carottes en bâtonnets 25 min avec le cumin et un filet d'huile.", "Dispose le quinoa, les carottes et les pois chiches dans le bol.", "Détends le tahini avec le citron et un peu d'eau, et nappe le bowl."] },
  { key: "din", slot: "Dîner", title: "Soupe thaï coco-citronnelle & légumes",
    sensation: "Parfumée, douce et acidulée, la coco qui enveloppe. Exotique et apaisante.",
    ingredients: [["Lait de coco", "15 cl"], ["Bouillon de légumes", "25 cl"], ["Citronnelle", "1 tige"], ["Champignons", "4"], ["Pak choï ou chou", "1 poignée"], ["Citron vert", "½"]],
    swaps: ["Pas de citronnelle ? → zeste de citron vert", "Pas de pak choï ? → épinards ou blettes"],
    why: "Un bouillon parfumé au lait de coco, plein de légumes : léger pour le soir, sans féculent ni laitage de vache, et la citronnelle aide à digérer.",
    steps: ["Chauffe le bouillon et le lait de coco avec la citronnelle écrasée.", "Ajoute les champignons et le chou, laisse cuire 8 min.", "Retire la citronnelle, ajoute un trait de citron vert et sers."] }
] },
// ============================ SEMAINE 2 · Énergie & Vitalité ============================
// J8
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Pommes fondantes à la cannelle & noix",
    sensation: "Tiède et parfumé, la pomme fondante sous la cannelle, les noix qui croquent. Réconfortant pour démarrer la semaine, sans rien de lourd.",
    ingredients: [["Pommes", "2"], ["Cannelle", "1 pincée"], ["Noix", "1 poignée"], ["Citron", "quelques gouttes"], ["Graines de courge", "1 c. à s."]],
    swaps: ["Pas de noix ? → amandes ou noisettes", "Plus gourmand ? → un filet de purée d'amande"],
    why: "Des fruits servis seuls le matin, juste tiédis et relevés d'oléagineux pour tenir : aucune céréale ni laitage de vache, on respecte la règle « fruits toujours seuls » tout en restant réconfortant.",
    steps: ["Coupe les pommes en quartiers et fais-les fondre 8 min à couvert avec un fond d'eau et la cannelle.", "Écrase grossièrement à la fourchette et ajoute un trait de citron.", "Parsème de noix concassées et de graines de courge, et déguste tiède."] },
  { key: "dej", slot: "Déjeuner", title: "Saumon vapeur, fenouil rôti & citron",
    sensation: "Fondant et iodé, le fenouil légèrement anisé. Fin, parfumé, jamais lourd.",
    ingredients: [["Pavé de saumon", "1"], ["Fenouil", "1 bulbe"], ["Citron", "1"], ["Aneth", "quelques brins"], ["Huile d'olive", "filet"]],
    swaps: ["Pas de saumon ? → truite ou maquereau", "Pas de fenouil ? → courgettes rôties"],
    why: "Une protéine animale (le poisson) avec des légumes, sans aucun féculent : on suit la règle « protéine animale + légumes, jamais avec un féculent ». Riche en bons oméga-3.",
    steps: ["Coupe le fenouil en quartiers et rôtis-le 25 min avec huile et citron.", "Cuis le saumon à la vapeur 8 à 10 min.", "Sers le saumon sur le fenueil, parsème d'aneth et de zeste de citron."] },
  { key: "din", slot: "Dîner", title: "Dahl de lentilles vertes aux épinards",
    sensation: "Épicé doux, fondant, les épinards qui apportent du vert. Nourrissant et apaisant.",
    ingredients: [["Lentilles vertes", "80 g"], ["Épinards", "2 poignées"], ["Oignon", "½"], ["Lait de coco", "10 cl"], ["Cumin & curcuma", "1 c. à c."], ["Ail", "1 gousse"]],
    swaps: ["Pas de lentilles vertes ? → lentilles corail (plus fondantes)", "Sans coco ? → un filet d'huile d'olive"],
    why: "Les lentilles sont une protéine végétale rassasiante : pas de protéine animale le soir, pas de laitage. Un dîner consistant mais digeste pour bien dormir.",
    steps: ["Fais revenir l'oignon, l'ail et les épices.", "Ajoute les lentilles rincées, couvre d'eau et laisse cuire 20 min.", "Incorpore les épinards et le lait de coco en fin de cuisson."] }
] },
// J9
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Chia pudding coco & mangue",
    sensation: "Onctueux, exotique, la mangue sucrée sur le chia crémeux. Une douceur solaire.",
    ingredients: [["Graines de chia", "2 c. à s."], ["Lait de coco", "15 cl"], ["Mangue", "½"], ["Citron vert", "quelques gouttes"]],
    swaps: ["Pas de mangue ? → fruits de saison bien mûrs", "Plus léger ? → lait d'amande à la place de la coco"],
    why: "Le chia gonfle et cale longtemps, sans aucun laitage de vache. La mangue, fruit servi seul au matin, apporte le sucre naturel et la couleur.",
    steps: ["La veille, mélange le chia et le lait de coco, laisse prendre au frais.", "Le matin, dépose la mangue en dés par-dessus.", "Ajoute quelques gouttes de citron vert et déguste frais."] },
  { key: "dej", slot: "Déjeuner", title: "Salade de riz sauvage, edamame & avocat",
    sensation: "Croquant et nourrissant, le sésame qui parfume, l'avocat qui adoucit. Vraiment complet.",
    ingredients: [["Riz sauvage cuit", "80 g"], ["Edamame", "3 c. à s."], ["Avocat", "½"], ["Graines de sésame", "1 c. à s."], ["Sauce tamari", "1 c. à c."], ["Citron", "½"]],
    swaps: ["Pas de riz sauvage ? → riz complet ou quinoa", "Pas d'edamame ? → pois chiches"],
    why: "Céréale et légumineuse (edamame), sans protéine animale : un duo végétal complet. Le tamari, sans blé, remplace la sauce soja classique pour rester sans gluten.",
    steps: ["Mélange le riz sauvage refroidi avec les edamame.", "Ajoute l'avocat en dés et arrose de tamari et de citron.", "Parsème de graines de sésame et mélange délicatement."] },
  { key: "din", slot: "Dîner", title: "Soupe de potimarron au gingembre",
    sensation: "Veloutée, douce, la chair du potimarron presque sucrée. Un bol orangé qui réconforte.",
    ingredients: [["Potimarron", "½"], ["Oignon", "½"], ["Gingembre frais", "1 cm"], ["Bouillon de légumes", "40 cl"], ["Graines de courge", "1 c. à s."], ["Huile d'olive", "filet"]],
    swaps: ["Pas de potimarron ? → butternut ou potiron", "Plus crémeux ? → un trait de lait de coco"],
    why: "Une soupe de légumes seule, sans féculent ajouté ni laitage : douce pour la digestion du soir, le gingembre réchauffe et apaise.",
    steps: ["Fais suer l'oignon et le gingembre, ajoute le potimarron en cubes.", "Couvre de bouillon, cuis 20 min puis mixe.", "Sers avec un filet d'huile et des graines de courge."] }
] },
// J10
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Bol de fruits & purée d'amande",
    sensation: "Frais et gourmand, la purée d'amande qui nappe les fruits. Simple et satisfaisant.",
    ingredients: [["Fruits de saison", "1 bol"], ["Purée d'amande", "1 c. à s."], ["Graines de courge", "1 c. à s."], ["Cannelle", "1 pincée"]],
    swaps: ["Pas de purée d'amande ? → purée de noisette", "Envie de croquant ? → quelques noix"],
    why: "Des fruits servis seuls le matin, juste relevés d'un peu de purée d'oléagineux pour tenir : l'énergie qui vient vite, sans alourdir.",
    steps: ["Coupe les fruits en morceaux dans un bol.", "Nappe d'un filet de purée d'amande.", "Parsème de graines de courge et de cannelle."] },
  { key: "dej", slot: "Déjeuner", title: "Filet de cabillaud & ratatouille",
    sensation: "Tendre et nacré, les légumes du soleil fondants et parfumés. Méditerranéen et léger.",
    ingredients: [["Filet de cabillaud", "1"], ["Courgette", "1"], ["Aubergine", "½"], ["Tomate", "1"], ["Poivron", "½"], ["Herbes de Provence", "1 pincée"]],
    swaps: ["Pas de cabillaud ? → lieu ou colin", "Pressé ? → ratatouille déjà prête, de qualité"],
    why: "Un poisson blanc avec des légumes mijotés, sans féculent : protéine animale et légumes, jamais avec un féculent. Léger et plein de saveurs.",
    steps: ["Fais mijoter les légumes en dés 25 min avec les herbes.", "Pose le cabillaud sur la ratatouille, couvre et cuis 8 min.", "Sers bien chaud, arrosé d'un filet d'huile d'olive."] },
  { key: "din", slot: "Dîner", title: "Quinoa aux légumes rôtis & herbes",
    sensation: "Coloré, parfumé, les légumes caramélisés par le four. Réconfortant sans être lourd.",
    ingredients: [["Quinoa cuit", "70 g"], ["Courgette", "1"], ["Poivron", "½"], ["Oignon rouge", "½"], ["Herbes fraîches", "1 poignée"], ["Huile d'olive", "filet"]],
    swaps: ["Pas de quinoa ? → millet ou sarrasin", "Plus de peps ? → un trait de citron"],
    why: "Céréale et légumes rôtis, sans protéine animale : un dîner végétal complet et doux pour la nuit, parfumé par les herbes fraîches.",
    steps: ["Rôtis les légumes en dés 25 min avec un filet d'huile.", "Mélange-les au quinoa cuit, encore tiède.", "Ajoute les herbes ciselées et un tour de moulin à poivre."] }
] },
// J11 — milieu de semaine 2 (rappel courses)
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Smoothie épinard-ananas-coco",
    sensation: "Tropical et frais, l'ananas qui pétille, la coco qui adoucit. Vitaminé dès le réveil.",
    ingredients: [["Ananas", "2 tranches"], ["Épinards frais", "1 poignée"], ["Lait de coco léger", "20 cl"], ["Citron vert", "½"], ["Gingembre", "1 cm"]],
    swaps: ["Pas d'ananas ? → mangue ou pomme", "Sans coco ? → eau de source"],
    why: "Un smoothie vert qui hydrate et reminéralise, avec juste assez de fruit pour le goût. Pas de laitage de vache : la coco fait le crémeux.",
    steps: ["Mets l'ananas, les épinards et le gingembre dans le blender.", "Verse le lait de coco et mixe jusqu'à onctuosité.", "Ajoute un trait de citron vert et bois frais."] },
  { key: "dej", slot: "Déjeuner", title: "Socca (galette de pois chiches) & salade verte",
    sensation: "Dorée et moelleuse à cœur, croustillante sur les bords, avec une salade qui croque. Réconfortant.",
    ingredients: [["Farine de pois chiche", "100 g"], ["Eau", "20 cl"], ["Huile d'olive", "2 c. à s."], ["Salade verte", "2 poignées"], ["Citron", "½"], ["Cumin", "1 pincée"]],
    swaps: ["Sans four ? → cuis à la poêle en petites galettes", "Plus garni ? → ajoute des tomates cerises"],
    why: "La socca est faite de farine de pois chiche : sans gluten et riche en protéines végétales, sans aucun produit animal. Servie avec une salade, elle cale sans peser.",
    steps: ["Mélange la farine, l'eau, l'huile et le cumin, laisse reposer 30 min.", "Verse en couche fine et cuis au four très chaud 12 min.", "Sers avec la salade assaisonnée de citron et d'huile d'olive."] },
  { key: "din", slot: "Dîner", title: "Curry de lentilles corail aux épinards",
    sensation: "Doux et crémeux, le vert des épinards dans le doré du curry. Enveloppant et apaisant.",
    ingredients: [["Lentilles corail", "80 g"], ["Épinards", "2 poignées"], ["Lait de coco", "12 cl"], ["Oignon", "½"], ["Curcuma & curry doux", "1 c. à c."], ["Gingembre", "1 cm"]],
    swaps: ["Pas d'épinards ? → blettes ou chou kale", "Plus relevé ? → une pointe de piment"],
    why: "Une protéine végétale (lentilles) mijotée à la coco, sans laitage ni protéine animale : un dîner consistant mais facile à digérer le soir.",
    steps: ["Fais revenir l'oignon, le gingembre et les épices.", "Ajoute les lentilles rincées et de l'eau, cuis 12 min.", "Incorpore les épinards et le lait de coco, laisse fondre 3 min."] }
] },
// J12
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Compote de fruits rouges & graines de courge",
    sensation: "Acidulée et tiède, les graines qui croquent. Une douceur vive et réconfortante.",
    ingredients: [["Fruits rouges", "1 bol"], ["Graines de courge", "1 c. à s."], ["Citron", "quelques gouttes"], ["Vanille", "1 pointe"]],
    swaps: ["Pas de fruits rouges ? → pomme et poire", "Envie de fondant ? → 1 c. à s. de purée d'amande"],
    why: "Une compote sans sucre ajouté, des fruits servis seuls le matin : tout le sucre vient des fruits, et les graines apportent un peu de tenue.",
    steps: ["Fais chauffer les fruits rouges 5 min à feu doux.", "Ajoute la vanille et un trait de citron.", "Verse dans un bol et parsème de graines de courge."] },
  { key: "dej", slot: "Déjeuner", title: "Omelette aux herbes & champignons poêlés",
    sensation: "Moelleuse et parfumée, les champignons dorés et fondants. Simple, chaud, rassasiant.",
    ingredients: [["Œufs", "2"], ["Champignons", "150 g"], ["Persil & ciboulette", "quelques brins"], ["Ail", "1 gousse"], ["Huile d'olive", "filet"]],
    swaps: ["Sans œufs ? → tofu brouillé", "Pas de champignons ? → courgettes en dés"],
    why: "Une protéine animale (l'œuf) servie avec des légumes, sans féculent : on respecte la règle. Les champignons apportent du moelleux sans alourdir.",
    steps: ["Poêle les champignons émincés avec l'ail jusqu'à ce qu'ils dorent.", "Bats les œufs avec les herbes, verse en omelette sur feu doux.", "Replie et sers avec les champignons par-dessus."] },
  { key: "din", slot: "Dîner", title: "Velouté de brocoli à l'huile de noisette",
    sensation: "Vert profond, soyeux, la noisette qui parfume. Léger et élégant pour le soir.",
    ingredients: [["Brocoli", "1"], ["Oignon", "½"], ["Bouillon de légumes", "40 cl"], ["Huile de noisette", "filet"], ["Noisettes torréfiées", "quelques-unes"]],
    swaps: ["Pas de brocoli ? → courgette ou épinards", "Pas d'huile de noisette ? → huile d'olive"],
    why: "Un velouté tout en légumes, sans féculent ni laitage : doux pour la digestion du soir, sublimé par la noisette qui apporte du parfum et du croquant.",
    steps: ["Fais suer l'oignon, ajoute le brocoli et le bouillon.", "Cuis 12 min puis mixe finement.", "Sers avec un filet d'huile de noisette et des noisettes concassées."] }
] },
// J13
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Poire pochée, noisettes & vanille",
    sensation: "Fondante et parfumée, la poire tiède sous la vanille, les noisettes torréfiées qui croquent. Une douceur tout en délicatesse.",
    ingredients: [["Poires", "2"], ["Vanille", "1 pointe"], ["Noisettes", "1 poignée"], ["Cannelle", "1 pincée"], ["Citron", "quelques gouttes"]],
    swaps: ["Pas de poire ? → pomme fondante", "Pas de noisettes ? → noix ou amandes"],
    why: "Des fruits servis seuls le matin, juste pochés et relevés d'oléagineux pour la tenue : ni céréale ni laitage, le sucre vient uniquement du fruit. La règle « fruits toujours seuls » respectée.",
    steps: ["Poche les poires en quartiers 8 min dans un peu d'eau avec la vanille.", "Égoutte, ajoute la cannelle et un trait de citron.", "Parsème de noisettes torréfiées concassées et déguste tiède."] },
  { key: "dej", slot: "Déjeuner", title: "Bowl de millet, courgette & menthe",
    sensation: "Frais et tendre, le millet moelleux, la menthe qui réveille. Léger et parfumé.",
    ingredients: [["Millet cuit", "80 g"], ["Courgette", "1"], ["Menthe fraîche", "quelques feuilles"], ["Amandes effilées", "1 c. à s."], ["Citron", "½"], ["Huile d'olive", "filet"]],
    swaps: ["Pas de millet ? → quinoa ou sarrasin", "Pas de menthe ? → basilic"],
    why: "Céréale et légumes, sans protéine animale : un déjeuner végétal complet et digeste, la menthe et le citron apportent la fraîcheur.",
    steps: ["Poêle la courgette en dés 6 min pour qu'elle reste croquante.", "Mélange-la au millet cuit avec la menthe ciselée.", "Assaisonne de citron et d'huile, parsème d'amandes effilées."] },
  { key: "din", slot: "Dîner", title: "Papillote de dorade aux légumes",
    sensation: "Tendre et parfumée, les légumes cuits dans leur jus, l'odeur qui s'échappe à l'ouverture. Délicat.",
    ingredients: [["Filet de dorade", "1"], ["Courgette", "½"], ["Tomate cerise", "6"], ["Fenouil", "¼"], ["Citron", "½"], ["Thym", "1 brin"]],
    swaps: ["Pas de dorade ? → bar ou cabillaud", "Pas de fenouil ? → poireau émincé"],
    why: "Un poisson cuit en papillote avec des légumes, sans féculent : la protéine animale et les légumes, jamais avec un féculent. La cuisson douce préserve tout le moelleux.",
    steps: ["Dépose le poisson sur les légumes émincés dans une feuille de cuisson.", "Ajoute le citron, le thym, un filet d'huile et referme la papillote.", "Cuis au four 18 min à 180 °C et ouvre à table."] }
] },
// J14 — fin de semaine 2
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Smoothie banane-cacao cru & amande",
    sensation: "Crémeux et chocolaté, gourmand sans culpabilité. Un réveil tout en douceur.",
    ingredients: [["Banane", "1"], ["Cacao cru", "1 c. à c."], ["Lait d'amande", "20 cl"], ["Purée d'amande", "1 c. à c."], ["Cannelle", "1 pincée"]],
    swaps: ["Sans cacao ? → une pointe de vanille", "Plus épais ? → ajoute une demi-banane congelée"],
    why: "Le cacao cru, non sucré, apporte le goût gourmand sans sucre raffiné. Avec le lait d'amande (zéro laitage), c'est un smoothie de fruit servi seul le matin.",
    steps: ["Mets la banane, le cacao et la purée d'amande dans le blender.", "Verse le lait d'amande et mixe jusqu'à onctuosité.", "Saupoudre de cannelle et bois frais."] },
  { key: "dej", slot: "Déjeuner", title: "Salade de quinoa, lentilles & poivrons rôtis",
    sensation: "Colorée et nourrissante, les poivrons fondants et sucrés, le persil qui rafraîchit. Complète.",
    ingredients: [["Quinoa cuit", "70 g"], ["Lentilles vertes cuites", "3 c. à s."], ["Poivrons rôtis", "½"], ["Persil", "1 poignée"], ["Citron", "½"], ["Huile d'olive", "filet"]],
    swaps: ["Pas de lentilles ? → pois chiches", "Pas de poivrons ? → tomates séchées"],
    why: "Céréale et légumineuse ensemble, sans protéine animale : un duo végétal complet et rassasiant, riche en fibres et en protéines, qui ne fermente pas.",
    steps: ["Mélange le quinoa et les lentilles refroidis.", "Ajoute les poivrons rôtis en lanières et le persil ciselé.", "Assaisonne de citron et d'huile d'olive."] },
  { key: "din", slot: "Dîner", title: "Soupe de carottes-coco au curcuma",
    sensation: "Orangée et douce, la coco qui enveloppe, le curcuma qui réchauffe. Réconfortante et apaisante.",
    ingredients: [["Carottes", "4"], ["Lait de coco", "12 cl"], ["Oignon", "½"], ["Curcuma & gingembre", "1 c. à c."], ["Bouillon de légumes", "30 cl"], ["Coriandre", "quelques brins"]],
    swaps: ["Plus de douceur ? → ajoute une patate douce", "Sans coco ? → un filet d'huile d'olive"],
    why: "Une soupe de légumes au lait de coco, sans laitage de vache ni protéine animale : douce et digeste pour le soir, le curcuma soutient l'apaisement.",
    steps: ["Fais suer l'oignon avec les épices, ajoute les carottes en rondelles.", "Couvre de bouillon, cuis 20 min puis mixe avec le lait de coco.", "Parsème de coriandre et sers bien chaud."] }
] },
// ============================ SEMAINE 3 · Ancrage & Performance ============================
// J15
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Bol de fruits de saison & oléagineux",
    sensation: "Frais, croquant, coloré. Le matin simple et efficace qu'on adopte pour de bon.",
    ingredients: [["Fruits de saison", "1 bol"], ["Mélange d'oléagineux", "1 poignée"], ["Graines de courge", "1 c. à s."], ["Citron", "quelques gouttes"]],
    swaps: ["Envie de fondant ? → 1 c. à s. de purée d'amande", "Plus parfumé ? → une pincée de cannelle"],
    why: "Le rituel du matin qui devient un réflexe : des fruits servis seuls pour l'énergie rapide, des oléagineux pour la tenue. Simple, sain, durable.",
    steps: ["Coupe les fruits en morceaux dans un bol.", "Ajoute les oléagineux et les graines.", "Réveille le tout d'un trait de citron."] },
  { key: "dej", slot: "Déjeuner", title: "Patate douce rôtie, pois chiches épicés & roquette",
    sensation: "Fondante et sucrée, les pois chiches croustillants et épicés, la roquette poivrée. Généreux et réconfortant.",
    ingredients: [["Patate douce", "1"], ["Pois chiches cuits", "4 c. à s."], ["Roquette", "2 poignées"], ["Paprika & cumin", "1 c. à c."], ["Tahini", "1 c. à s."], ["Citron", "½"]],
    swaps: ["Pas de patate douce ? → courge butternut", "Pas de tahini ? → purée d'amande"],
    why: "Un féculent végétal (patate douce) et une légumineuse, sans protéine animale : conforme à la méthode, et tellement rassasiant qu'on tient sans fringale.",
    steps: ["Rôtis la patate douce en cubes et les pois chiches épicés 25 min.", "Dépose-les sur la roquette.", "Détends le tahini au citron et un peu d'eau, et nappe l'assiette."] },
  { key: "din", slot: "Dîner", title: "Wok de légumes croquants au tofu & sésame",
    sensation: "Croquant et parfumé, le tofu doré, le sésame qui grille. Vif et satisfaisant.",
    ingredients: [["Tofu ferme", "120 g"], ["Brocoli", "½"], ["Carotte", "1"], ["Pois gourmands", "1 poignée"], ["Sauce tamari", "1 c. à s."], ["Graines de sésame", "1 c. à s."]],
    swaps: ["Pas de tofu ? → tempeh", "Pas de pois gourmands ? → haricots verts"],
    why: "Une protéine végétale (tofu) et des légumes sautés rapidement, sans laitage ni protéine animale. Le tamari, sans blé, garde le plat sans gluten.",
    steps: ["Saisis le tofu en dés jusqu'à ce qu'il dore, réserve.", "Fais sauter les légumes vifs 5 min pour qu'ils restent croquants.", "Remets le tofu, déglace au tamari et parsème de sésame."] }
] },
// J16
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Chia-coco & fruits frais",
    sensation: "Crémeux et frais, les fruits qui apportent le pep's sur le chia fondant. Doux et tenace.",
    ingredients: [["Graines de chia", "2 c. à s."], ["Lait de coco", "15 cl"], ["Fruits de saison", "½ bol"], ["Citron vert", "quelques gouttes"]],
    swaps: ["Pas de chia ? → graines de lin moulues", "Plus léger ? → lait d'amande"],
    why: "Le chia cale longtemps sans laitage de vache, et les fruits servis seuls le matin apportent la fraîcheur et le sucre naturel. Un petit-déjeuner qui tient.",
    steps: ["La veille, mélange le chia et le lait de coco, laisse prendre au frais.", "Le matin, ajoute les fruits frais coupés.", "Termine par un trait de citron vert."] },
  { key: "dej", slot: "Déjeuner", title: "Pavé de saumon, courgettes & fenouil",
    sensation: "Fondant et iodé, les légumes poêlés tout juste tendres. Fin, léger, satisfaisant.",
    ingredients: [["Pavé de saumon", "1"], ["Courgette", "1"], ["Fenouil", "½ bulbe"], ["Citron", "1"], ["Aneth", "quelques brins"], ["Huile d'olive", "filet"]],
    swaps: ["Pas de saumon ? → truite", "Pas de fenouil ? → poireau"],
    why: "Poisson et légumes, sans aucun féculent : protéine animale + légumes, jamais avec un féculent. Riche en oméga-3, parfait pour la performance.",
    steps: ["Poêle la courgette et le fenuil émincés 8 min.", "Cuis le saumon à la poêle ou vapeur 8 min.", "Sers ensemble avec l'aneth, le zeste et un trait de citron."] },
  { key: "din", slot: "Dîner", title: "Velouté de panais & noisettes torréfiées",
    sensation: "Soyeux et légèrement sucré, le panais doux, la noisette grillée qui parfume. Élégant et réconfortant.",
    ingredients: [["Panais", "2"], ["Oignon", "½"], ["Bouillon de légumes", "40 cl"], ["Noisettes", "quelques-unes"], ["Huile de noisette", "filet"], ["Muscade", "1 pointe"]],
    swaps: ["Pas de panais ? → topinambour ou carotte", "Sans huile de noisette ? → huile d'olive"],
    why: "Une soupe de légumes seule, sans féculent ajouté ni laitage : douce pour le soir, la noisette torréfiée apporte le parfum et le croquant.",
    steps: ["Fais suer l'oignon, ajoute le panais en morceaux et le bouillon.", "Cuis 20 min puis mixe avec une pointe de muscade.", "Sers avec un filet d'huile de noisette et des noisettes concassées."] }
] },
// J17
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Bananes tièdes, amandes & cannelle",
    sensation: "Fondantes et sucrées, les bananes juste tiédies, la cannelle qui réchauffe, les amandes qui croquent. Une douceur tout doux pour le réveil.",
    ingredients: [["Bananes", "2"], ["Cannelle", "1 pincée"], ["Amandes", "1 poignée"], ["Citron", "quelques gouttes"], ["Graines de courge", "1 c. à s."]],
    swaps: ["Pas de banane ? → poire fondante", "Pas d'amandes ? → noisettes ou noix"],
    why: "Des fruits servis seuls le matin, à peine tiédis et relevés d'oléagineux pour tenir : aucune céréale ni laitage de vache, le sucre vient uniquement du fruit. La règle « fruits toujours seuls » respectée.",
    steps: ["Coupe les bananes en rondelles et fais-les tiédir 3 min à la poêle avec la cannelle, sans matière grasse.", "Dépose dans un bol et ajoute un trait de citron.", "Parsème d'amandes concassées et de graines de courge, et déguste tiède."] },
  { key: "dej", slot: "Déjeuner", title: "Bowl de riz complet, haricots rouges & avocat",
    sensation: "Nourrissant et coloré, les haricots fondants, l'avocat crémeux, la coriandre fraîche. Style mexicain doux.",
    ingredients: [["Riz complet cuit", "80 g"], ["Haricots rouges cuits", "3 c. à s."], ["Avocat", "½"], ["Tomate", "1"], ["Coriandre", "quelques brins"], ["Citron vert", "½"]],
    swaps: ["Pas de riz complet ? → quinoa", "Pas de haricots rouges ? → haricots noirs"],
    why: "Céréale et légumineuse ensemble, sans protéine animale : un duo végétal complet, riche et rassasiant, qui tient toute l'après-midi sans fermenter.",
    steps: ["Dépose le riz complet tiède au fond du bol.", "Ajoute les haricots rouges, la tomate et l'avocat en dés.", "Parsème de coriandre et arrose de citron vert."] },
  { key: "din", slot: "Dîner", title: "Soupe de lentilles au cumin & citron",
    sensation: "Réconfortante et parfumée, le cumin qui chauffe, le citron qui éclaire. Pleine et douce à la fois.",
    ingredients: [["Lentilles corail", "70 g"], ["Carotte", "1"], ["Oignon", "½"], ["Cumin", "1 c. à c."], ["Citron", "½"], ["Bouillon de légumes", "40 cl"]],
    swaps: ["Pas de lentilles corail ? → lentilles vertes", "Plus relevé ? → une pointe de piment doux"],
    why: "Une protéine végétale (lentilles) en soupe, sans protéine animale ni laitage : un dîner consistant mais digeste, le citron apporte la touche vive en fin de cuisson.",
    steps: ["Fais suer l'oignon et la carotte avec le cumin.", "Ajoute les lentilles et le bouillon, cuis 15 min puis mixe à moitié.", "Hors du feu, ajoute le jus de citron et sers chaud."] }
] },
// J18 — milieu de semaine 3 (rappel courses)
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Smoothie vert kiwi-épinard-concombre",
    sensation: "Vif et désaltérant, le kiwi acidulé, le concombre rafraîchissant. Un coup de fouet vert.",
    ingredients: [["Kiwi", "2"], ["Épinards frais", "1 poignée"], ["Concombre", "½"], ["Citron", "½"], ["Eau de source", "15 cl"]],
    swaps: ["Pas de kiwi ? → pomme verte", "Plus doux ? → une demi-banane"],
    why: "Un jus vert peu sucré qui hydrate et reminéralise : on garde le réflexe détox même en semaine 3. Le fruit reste « seul » dans le repas du matin.",
    steps: ["Mixe le kiwi, les épinards et le concombre avec l'eau.", "Ajoute un trait de citron.", "Bois aussitôt, bien frais."] },
  { key: "dej", slot: "Déjeuner", title: "Œufs durs, asperges rôties & vinaigrette moutarde",
    sensation: "Tendre et printanier, les asperges légèrement grillées, la vinaigrette relevée. Fin et léger.",
    ingredients: [["Œufs", "2"], ["Asperges vertes", "1 botte"], ["Moutarde", "1 c. à c."], ["Citron", "½"], ["Huile d'olive", "filet"], ["Graines de courge", "1 c. à s."]],
    swaps: ["Pas d'asperges ? → haricots verts ou brocoli", "Sans œufs ? → avocat et pois chiches rôtis"],
    why: "Une protéine animale (l'œuf) avec des légumes, sans aucun féculent : conforme à la règle. Les asperges apportent fraîcheur et fibres.",
    steps: ["Cuis les œufs durs 9 min et rafraîchis-les.", "Rôtis les asperges 12 min avec un filet d'huile.", "Émulsionne moutarde, citron et huile, et nappe le tout."] },
  { key: "din", slot: "Dîner", title: "Curry de légumes & pois chiches au lait de coco",
    sensation: "Doré et parfumé, les légumes fondants, les pois chiches qui tiennent. Enveloppant et nourrissant.",
    ingredients: [["Pois chiches cuits", "4 c. à s."], ["Courgette", "1"], ["Carotte", "1"], ["Lait de coco", "12 cl"], ["Curry doux & curcuma", "1 c. à c."], ["Coriandre", "quelques brins"]],
    swaps: ["Pas de pois chiches ? → lentilles corail", "Plus de légumes ? → ajoute des épinards"],
    why: "Légumes et légumineuse mijotés à la coco, sans laitage ni protéine animale : un dîner consistant mais digeste, idéal pour finir la journée en douceur.",
    steps: ["Fais revenir les épices, ajoute les légumes en dés.", "Verse le lait de coco et les pois chiches, mijote 15 min.", "Parsème de coriandre et sers bien chaud."] }
] },
// J19
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Bol de fruits rouges & amandes",
    sensation: "Acidulé et croquant, les fruits rouges vifs, les amandes qui calent. Frais et vitaminé.",
    ingredients: [["Fruits rouges", "1 bol"], ["Amandes", "1 poignée"], ["Graines de chia", "1 c. à c."], ["Citron", "quelques gouttes"]],
    swaps: ["Hors saison ? → fruits rouges surgelés décongelés", "Pas d'amandes ? → noisettes"],
    why: "Des fruits rouges servis seuls le matin, peu sucrés et riches en antioxydants, avec des amandes pour tenir : la règle « fruits toujours seuls » respectée à la lettre.",
    steps: ["Dépose les fruits rouges dans un bol.", "Parsème d'amandes concassées et de chia.", "Ajoute quelques gouttes de citron et déguste frais."] },
  { key: "dej", slot: "Déjeuner", title: "Salade de sarrasin, betterave & noix",
    sensation: "Terreuse et fraîche, la betterave sucrée, les noix qui croquent, les herbes qui parfument. Complète.",
    ingredients: [["Sarrasin cuit", "80 g"], ["Betterave cuite", "1"], ["Noix", "1 poignée"], ["Herbes fraîches", "1 poignée"], ["Huile de noix", "filet"], ["Citron", "½"]],
    swaps: ["Pas de sarrasin ? → quinoa ou millet", "Pas de noix ? → graines de courge"],
    why: "Sarrasin (sans gluten) et légumes, sans protéine animale : un déjeuner végétal complet et coloré, riche en fibres, doux pour la digestion.",
    steps: ["Mélange le sarrasin refroidi avec la betterave en dés.", "Ajoute les noix concassées et les herbes ciselées.", "Assaisonne d'huile de noix et de citron."] },
  { key: "din", slot: "Dîner", title: "Filet de truite & fondue de poireaux",
    sensation: "Tendre et délicat, les poireaux fondants et doux. Une assiette tout en finesse pour le soir.",
    ingredients: [["Filet de truite", "1"], ["Poireaux", "2"], ["Citron", "½"], ["Aneth", "quelques brins"], ["Huile d'olive", "filet"], ["Graines de courge", "1 c. à s."]],
    swaps: ["Pas de truite ? → cabillaud ou dorade", "Pas de poireaux ? → fenouil émincé"],
    why: "Un poisson avec des légumes fondants, sans féculent : protéine animale + légumes, jamais avec un féculent. Léger et parfait pour finir la journée en douceur.",
    steps: ["Fais fondre les poireaux émincés 12 min à feu doux.", "Cuis la truite à la poêle 6 min côté peau.", "Sers sur la fondue de poireaux avec l'aneth et un trait de citron."] }
] },
// J20
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Compote pomme-cannelle & purée de noisette",
    sensation: "Tiède et fondante, la cannelle parfumée, la noisette gourmande. Une douceur réconfortante.",
    ingredients: [["Pommes", "2"], ["Cannelle", "1 pincée"], ["Purée de noisette", "1 c. à c."], ["Citron", "quelques gouttes"], ["Graines de courge", "1 c. à s."]],
    swaps: ["Pas de pomme ? → poire", "Pas de purée de noisette ? → purée d'amande"],
    why: "Une compote maison sans sucre ajouté, des fruits servis seuls le matin : le sucre vient du fruit, la purée de noisette apporte gourmandise et tenue.",
    steps: ["Compote les pommes 10 min avec un fond d'eau.", "Écrase, ajoute la cannelle et un trait de citron.", "Nappe d'un filet de purée de noisette et parsème de graines."] },
  { key: "dej", slot: "Déjeuner", title: "Buddha bowl quinoa, edamame & carotte",
    sensation: "Coloré et complet, le quinoa moelleux, les edamame tendres, le tahini qui lie. Satisfaisant et frais.",
    ingredients: [["Quinoa cuit", "80 g"], ["Edamame", "3 c. à s."], ["Carotte râpée", "1"], ["Avocat", "½"], ["Tahini", "1 c. à s."], ["Citron", "½"]],
    swaps: ["Pas d'edamame ? → pois chiches", "Pas de tahini ? → purée d'amande"],
    why: "Céréale et légumineuse (edamame), sans protéine animale : un bowl végétal complet et équilibré, riche en protéines et en fibres, qui tient l'après-midi.",
    steps: ["Dispose le quinoa, la carotte râpée et les edamame dans le bol.", "Ajoute l'avocat en lamelles.", "Détends le tahini au citron et nappe le bowl."] },
  { key: "din", slot: "Dîner", title: "Velouté de butternut, sauge & graines",
    sensation: "Velouté et doux, la courge presque sucrée, la sauge qui parfume. Chaleureux et apaisant.",
    ingredients: [["Courge butternut", "½"], ["Oignon", "½"], ["Sauge", "quelques feuilles"], ["Bouillon de légumes", "40 cl"], ["Graines de courge", "1 c. à s."], ["Huile d'olive", "filet"]],
    swaps: ["Pas de butternut ? → potimarron", "Plus crémeux ? → un trait de lait de coco"],
    why: "Une soupe de légumes seule, sans féculent ni laitage : douce et digeste pour le soir. La sauge parfume et les graines apportent du croquant.",
    steps: ["Fais suer l'oignon, ajoute la courge en cubes et la sauge.", "Couvre de bouillon, cuis 20 min puis mixe.", "Sers avec un filet d'huile et des graines de courge."] }
] },
// J21 — dernier jour, célébration
{ meals: [
  { key: "pdj", slot: "Petit-déjeuner", title: "Grand bol de fruits de saison & graines",
    sensation: "Festif et coloré, gorgé de fraîcheur et d'énergie. Le matin d'un jour qu'on savoure.",
    ingredients: [["Fruits de saison variés", "1 grand bol"], ["Graines de courge & tournesol", "2 c. à s."], ["Menthe", "quelques feuilles"], ["Citron vert", "½"]],
    swaps: ["Envie de fondant ? → 1 c. à s. de purée d'amande", "Plus parfumé ? → un peu de basilic"],
    why: "Pour ce dernier matin, le rituel devenu réflexe : des fruits servis seuls, variés et colorés, pour l'énergie et le plaisir. C'est ce que tu emportes pour la suite.",
    steps: ["Coupe une belle variété de fruits dans un grand bol.", "Parsème de graines et de menthe ciselée.", "Réveille d'un trait de citron vert et savoure."] },
  { key: "dej", slot: "Déjeuner", title: "Bowl arc-en-ciel, pois chiches rôtis & avocat",
    sensation: "Généreux et coloré, les pois chiches croustillants, l'avocat crémeux, tout qui croque et fond. Une fête dans l'assiette.",
    ingredients: [["Quinoa cuit", "80 g"], ["Pois chiches rôtis", "4 c. à s."], ["Avocat", "½"], ["Chou rouge & carotte", "1 poignée"], ["Graines de courge", "1 c. à s."], ["Citron & huile d'olive", "filet"]],
    swaps: ["Pas de quinoa ? → riz complet ou sarrasin", "Pas de pois chiches ? → edamame"],
    why: "Céréale, légumineuse et légumes hauts en couleur, sans protéine animale : le bowl emblématique de la méthode, complet et rassasiant. De quoi célébrer en beauté.",
    steps: ["Rôtis les pois chiches épicés 25 min jusqu'à ce qu'ils croustillent.", "Dispose le quinoa, les crudités et l'avocat dans le bol.", "Ajoute les pois chiches, les graines, et assaisonne de citron et d'huile."] },
  { key: "din", slot: "Dîner", title: "Curry doux de légumes au lait de coco & riz basmati",
    sensation: "Doré, parfumé, enveloppant : le repas qui clôt le programme en beauté, réconfortant et chaleureux.",
    ingredients: [["Riz basmati cuit", "70 g"], ["Légumes variés", "2 poignées"], ["Lait de coco", "15 cl"], ["Curry doux & curcuma", "1 c. à c."], ["Gingembre", "1 cm"], ["Coriandre", "quelques brins"]],
    swaps: ["Pas de basmati ? → riz complet", "Plus de protéines ? → ajoute des pois chiches"],
    why: "Un curry de légumes avec un peu de riz, sans protéine animale ni laitage de vache : un dîner festif mais conforme, tout en douceur pour finir ces 21 jours.",
    steps: ["Fais revenir le gingembre et les épices, ajoute les légumes en dés.", "Verse le lait de coco, mijote 15 min.", "Sers sur le riz basmati et parsème de coriandre fraîche."] }
] }
];

// photos : vrais visuels quand on les a (champ photo du repas), sinon les 3 visuels
// de référence réutilisés par moment de la journée
const BTE_PHOTOS = { pdj: "images/petit-dej-fruits.png", dej: "images/dejeuner-buddha.jpg", din: "images/diner-dal.jpg" };
DAYS.forEach((d) => d.meals.forEach((m) => { if (!m.photo) m.photo = BTE_PHOTOS[m.key]; }));

window.BTE_DAYS = DAYS;
